version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/MY-git-project

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user